site_name: bash-helpers
site_author: Alan Guedes
site_url: http://alanlivio.github.io/bash-helpers
site_description: bash-helpers website
copyright: MIT
remote_branch: gh-pages
repo_url: https://github.com/alanlivio/bash-helpers
edit_uri: edit/master/docs/mkdocs
docs_dir: mkdocs

plugins:
  - search
  - macros:
      include_dir: ../

theme:
  name: material
  logo: logo.svg
  locale: en
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  nav_style: dark

extras:
  provider: google
  property: G-P8VQHVLPZD
