name: ci
on:
  push:
    branches:
      - master
    paths:
      - "docs/*"
      - "README.md"
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
