name: ci
on:
  push:
    branches:
      - master
    paths:
      - 'docs/*'
      - 'mkdocs.yaml'
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r mkdocs-reqs.txt
      - run: mkdocs gh-deploy --force
